version: "3"

services:
  watchman:
    image: lbry/watchman:latest
    container_name: watchman
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - "geoip_data:/app/geoip_data:ro"
  # influxdb:
  #   image: influxdb:2.0
  #   container_name: influxdb
  #   restart: on-failure
  #   ports:
  #     - "8086:8086"
  #   volumes:
  #     - influxdb2_data:/var/lib/influxdb2
  #     - influxdb2_config:/etc/influxdb2
  clickhouse:
    image: yandex/clickhouse-server:21.3
    container_name: clickhouse
    restart: on-failure
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - "clickhouse_data:/var/lib/clickhouse"
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: on-failure
    ports:
      - "8086:8086"
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2
      # environment:
        #   - DOCKER_INFLUXDB_INIT_MODE=setup
        #   - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
        #   - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
        #   - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
        #   - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
  grafana:
    image: grafana/grafana:7.5.4
    container_name: grafana
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    volumes:
      - "grafana_data:/var/lib/grafana"
  geoipupdate:
    image: "maxmindinc/geoipupdate:v4.7.1"
    # Override the entrypoint in order to avoid using envvars for config.
    # Futz with settings so we can keep mmdb and conf in same dir on host
    # (image looks for them in separate dirs by default).
    entrypoint:
      ["/usr/bin/geoipupdate", "-d", "/geoip_data", "-f", "/conf/GeoIP.conf"]
    volumes:
      - "./geoip:/conf"
      - "./geoip_data:/geoip_data"
      # - "geoip_data:/geoip_data"

volumes:
  influxdb2_data: {}
  influxdb2_config: {}
  grafana_data: {}
  clickhouse_data: {}
  geoip_data: {}
