name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GOROOT: /usr/local/go
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Get service name
        id: service
        run: echo "::set-output name=service::$(git describe --tags|sed -e 's/\-v.*//')"

      - name: Get service version
        id: version
        run: echo "::set-output name=version::$(git describe --tags|sed -e 's/.*\-v//')"

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      # odysee-api docker deployment

      - name: Build odysee-api
        if: steps.service.outputs.service == 'api'
        run: |
          go get github.com/gobuffalo/packr/v2/packr2@v2.7.1
          goreleaser build --rm-dist --snapshot

      - name: Build odysee-api docker image
        if: steps.service.outputs.service == 'api'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lbry/odysee-api
          tags: b-${{ github.base_ref }}
